blank_issues_enabled: false
contact_links:
  - name: 提问流程
    url: https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题
    about: 提问前必看
  - name: LaTeX 知识小站
    url: https://github.com/mohuangrui/ucasthesis/wiki
    about: 提问前必读
  - name: 已关闭问题 (closed issue)
    url: https://github.com/mohuangrui/ucasthesis/issues?q=
    about: 提问前必搜
